### ISSUE TITLE
Add tracking fields to models

### ISSUE THREAD

**Issue by amstilp** [UW-GAC/django-anvil-consortium-manager#47]
Implement some fields for tracking purposes. Some ideas:
- [x] Timestamp when the model instance was created
- [x] ~~User who created the model instance~~ - handled by simple-history
- [x] Timestamp when the model instance was updated
- [x] ~~User who updated a model instance~~ - handled by simple-history
- [x] ~~Timestamp when the AnVIL API call succeeded~~ - too complicated for now
- [x] ~~Timestamp when the model was created on the AnVIL platform (vs created in the Django database)~~ - not worth it
- [x] ~~Timestamp when the model was imported from AnVIL~~ - not worth it
- [x] ~~Indicator of whether a model was created by the app or imported from AnVIL~~ - handled by other fields (i.e. does the app have permission to modify)
